<?php

function ratings_block_block_info() {
  // This is our ratings block
  $blocks['rating_form'] = array(
    'info' => t('Rating Form'),
  );

  // This is our ratings block
  $blocks['weather'] = array(
    'info' => t('Toronto Weather'),
  );

  return $blocks;
}

function ratings_block_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'weather':

      // Get our weather from json feed.
      $weather = ratings_block_get_weather();

      // Define our subject.
      $block['subject'] = t('Toronto Weather');
      // Define what the content of our block will be.
      $block['content'] = 'Toronto weather is ' . $weather . 'º';

      break;
      // Add required "node" files from node module.
    case 'rating_form':
      // Add required "node" files from node module.
      module_load_include('inc', 'node', 'node.pages');
      // Define our content type.
      $type = 'wc_ratings';
      // Create a node object... notice the type casting using (object).
      $node = (object) array(
        'type' => $type,
        'language' => LANGUAGE_NONE,
      );
      // Get the form from Drupal... using drupal_get_form.
      // NOTE: For node forms we need to send a node object.
      $form = drupal_get_form($type . '_node_form', $node);
      // Define our subject.
      $block['subject'] = t('Add a rating');
      // Define what the content of our block will be.
      $block['content']['form'] = $form;

      break;
  }
  return $block;
}

function ratings_block_get_weather() {
  $data = drupal_http_request('http://api.openweathermap.org/data/2.5/forecast/daily?q=Toronto%20ON&mode=json&units=metric&cnt=7');
  $json = drupal_json_decode($data->data);
  dsm($json);

  return $json['list'][0]['temp']['day'];
}
